[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package_tlivroze"
version = "0.0.1"
authors = [
  { name="Theodore Livrozet", email="tlivroze@student.42.fr" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "MIT"}
license-files = ["LICENSE"]

[tool.hatch.build.targets.wheel]
packages = ["src/package_tlivroze"]